# Generated by Django 5.2.11 on 2026-03-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Name', max_length=100),
            preserve_default=False,
        ),
    ]
