# Generated by Django 5.2.11 on 2026-03-22 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('ON_TIME', 'On Time'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('NOT_MARKED', 'Not Marked')], max_length=20)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('movement_state', models.CharField(choices=[('INSIDE', 'Inside Hostel'), ('TEMP_LEFT', 'Temporarily Left'), ('VIOLATION', 'Violation Confirmed')], default='INSIDE', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
