# Generated by Django 5.2.11 on 2026-03-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='block',
            field=models.CharField(default='BHEEMA', max_length=50),
            preserve_default=False,
        ),
    ]
